### PR TITLE
Swift 2.0 syntax updates

### PR DESCRIPTION
**Pull request by kfarst**
- [x] Uses updated `do/catch` syntax for handling JSON serialization errors
- [x] Updates optionals syntax for `JSONObjectWithData` definition

### CODE REVIEW

**Comment by hallas** [comment]
Hey man. I'm working on an updated version but thanks a lot. Does this compile 100% with newest Swift?

**Comment by kfarst** [comment]
No problem! Yes it does, those updates are from a project I just started in XCode 7. There were still a few warnings but no build fails.

**Comment by hallas** [comment]
@kfarst I hope I'll find time to review this weekend :-)

**Comment by hallas** [comment]
Will look at getting this in without using the PR

**Pull request closed without merging**
